[package]
name = "trans"
version = "0.1.0"
edition = "2021"
default-run = "trans"

[dependencies]
cpal = "0.15"
crossbeam-channel = "0.5"
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true